// Fase 7, Task 3 (uitgebreid in de SEO/GEO-fase): voorbeeldcontent voor /blog. Er is geen CMS
// in deze codebase en dat wordt met deze posts ook niet geintroduceerd: een vaste lijst is
// genoeg voor een grid-overzicht en een artikel-template, en een echte redactieworkflow is een
// aparte beslissing voor later. De laatste drie (kanaalsynergie, RSA-assets, KPI-relaties) zijn
// gericht geschreven op zoekopdrachten en LLM-vragen van een specialist die naar precies dit
// probleem zoekt, en zijn gegrond in echte, bestaande analysecapaciteit (lib/cross-channel/
// funnel-overlap.ts, rsa-insights-facts.ts, lib/analysis/kpi-relations) -- geen verzonnen
// klantcijfers of onderzoeksclaims, ook hier niet.

export interface RelatedPage {
  label: string;
  href: string;
}

export interface BlogPost {
  slug: string;
  titel: string;
  samenvatting: string;
  datum: string;
  leesminuten: number;
  inhoud: string[];
  /** Slugs of other posts that genuinely share a theme -- not "the other five", picked per post. */
  gerelateerdeSlugs?: string[];
  /** Product pages the post's own content actually points to (audit, 11 August 2026: every post
   *  dead-ended before this -- the only link on the whole page was "back to all articles"). Left
   *  empty where nothing on the page is a real match, rather than forcing one. */
  gerelateerdePaginas?: RelatedPage[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "gemiddelde-cpa-verkeerde-vraag",
    titel: "Why an average CPA is the wrong question",
    samenvatting:
      "A single monthly CPA number averages two very different accounts into the same outcome. What that hides, and what to look at instead.",
    datum: "2026-06-02",
    leesminuten: 6,
    inhoud: [
      "A campaign with a CPA of 40 euros can describe two very different accounts: one that sits stably " +
        "around 40 euros everywhere, and one that hits 15 euros on desktop during the day and 90 on mobile " +
        "in the evening. The average is the same number in both cases, and the wrong question to ask in " +
        "both cases.",
      "The question that does work is a breakdown: by time of day, by device, and where relevant by " +
        "audience. Not because more detail is always better, but because a bid strategy at account level " +
        "reacts to the average, while costs are generated by time of day and device. A tROAS target that " +
        "fits the average therefore does not really fit either segment.",
      "In practice this means: before adjusting a bid strategy, first split the period where the problem " +
        "occurred by time of day and device. A spike confined to a few evening hours on mobile calls for a " +
        "different fix than a structurally too-high CPA across the whole day. Ctrl PPC's 6-step Decision " +
        "Framework builds on this: the hypothesis that follows from a signal points to the segment where the " +
        "problem actually sits, not to the account as a whole.",
    ],
    // Noemt het 6-staps Decision Framework zelf; verwijst naar waar dat staat uitgelegd. De twee
    // andere posts delen hetzelfde onderwerp: een gemiddelde/totaal dat de echte oorzaak verbergt.
    gerelateerdeSlugs: ["impression-share-dashboard-vertelt-niet", "acht-kpi-relaties-die-rapportages-missen"],
    gerelateerdePaginas: [{ label: "The 6-step Decision Framework", href: "/" }],
  },
  {
    slug: "impression-share-dashboard-vertelt-niet",
    titel: "What a dashboard does not tell you about impression share",
    samenvatting:
      "Impression share drops, and the dashboard shows a red line. The reason why is usually missing, and that reason determines which action makes sense.",
    datum: "2026-06-24",
    leesminuten: 5,
    inhoud: [
      "Search impression share drops for one of two reasons: budget or rank. A dashboard that only shows " +
        "the percentage forces you to guess which one it is, and the wrong guess spends money in the wrong " +
        "direction. Fixing a budget problem with a higher bid raises CPC without removing the underlying " +
        "shortfall; fixing a rank problem with more budget raises spend without winning back impressions.",
      "The distinction lives in two separate metrics that Google Ads does provide: search impression share " +
        "lost to budget, and search impression share lost to rank. Both are rarely visible in a standard " +
        "overview, and that is exactly where the \"dashboard illusion\" comes from: the screen shows an " +
        "outcome, not the two metrics that pull the cause apart.",
      "Once the cause is known, the next step is unambiguous: for budget, the question is whether the extra " +
        "spend is worth the margin; for rank, the question is whether the bid, the ad quality, or both are " +
        "falling short. Two very different conversations, both landing on the same red number on an average " +
        "dashboard.",
    ],
    // De post noemt "de dashboard illusion" letterlijk als specifieke claim (het scherm toont een
    // uitkomst, niet de twee metrics die de oorzaak uit elkaar trekken) -- dat blijft correct.
    // De sectienaam op /vs zelf is intussen herzien (11 augustus 2026, zie de comment daar); het
    // linklabel hieronder volgt die herziening.
    gerelateerdeSlugs: ["gemiddelde-cpa-verkeerde-vraag", "acht-kpi-relaties-die-rapportages-missen"],
    gerelateerdePaginas: [{ label: "Beyond the dashboard layer, in full", href: "/vs" }],
  },
  {
    slug: "attributie-zonder-trackingcode",
    titel: "Attribution without a tracking code: what change history tells you",
    samenvatting:
      "You do not need to manually log every change to know whether a hypothesis was executed. The change history the platform already keeps tells you.",
    datum: "2026-07-15",
    leesminuten: 7,
    inhoud: [
      "Every ad platform keeps a change history: what was changed, when, and by whom. That history is " +
        "rarely used for anything besides an after-the-fact audit, even though it is also the missing link " +
        "between a hypothesis and the result it predicted.",
      "The problem this solves: a metric can improve without the proposed change ever having been made, " +
        "and a metric can stay flat while the change was made but gets overshadowed by something else. " +
        "Without pulling in the change history, an improved metric after accepting a hypothesis is not " +
        "confirmation, at best a coincidence that looks suspiciously like one.",
      "The approach is not complicated, but it does require discipline: classify every change by the type " +
        "the hypothesis predicted (budget, bid, status, keyword), limit that to the window between accepting " +
        "the hypothesis and the measurement moment, and treat \"no matching change found\" as its own " +
        "outcome, not a hidden \"no\". That last step is where most attribution attempts run aground: an " +
        "unexecuted hypothesis still gets judged on numbers that had nothing to do with it.",
    ],
    // De FAQ beantwoordt vrijwel dezelfde vraag ("hoe weet ik of een hypothese echt werkte") in
    // net andere bewoordingen -- een lezer die dit artikel uitleest heeft die vraag al gesteld.
    gerelateerdeSlugs: ["kanaalsynergie-bewijzen", "rsa-asset-dubbeltelling"],
    gerelateerdePaginas: [{ label: "How do I know a hypothesis actually worked?", href: "/faq" }],
  },
  {
    slug: "kanaalsynergie-bewijzen",
    titel: "Proving channel synergy between Google, Meta, and LinkedIn",
    samenvatting:
      "Every channel delivers its own report, and no report shows whether the channels reinforce each other or double-pay for the same warm audience. A concrete way to actually see it.",
    datum: "2026-07-28",
    leesminuten: 8,
    inhoud: [
      "Ask a specialist whether their channels reinforce each other, and the answer is almost always a " +
        "feeling, not a number. Google Ads reports on Google Ads, Meta reports on Meta, and neither knows " +
        "the other exists. Proving channel synergy does not mean \"one more report\"; it means a layer that " +
        "looks at the same question across channels.",
      "That question breaks down into three roles every campaign, on every channel, effectively plays: " +
        "prospecting (tapping new demand), retargeting (recapturing a warm audience), and branded capture " +
        "(catching demand that already existed, on your own brand name). You can classify a campaign into " +
        "one of the three from its own signals: running on your own brand terms makes it branded capture. " +
        "Targeting a custom audience, site visitors, or a customer list makes it retargeting. A broad or " +
        "lookalike audience, or a demand-generating campaign type (display, video, demand gen), makes it " +
        "prospecting.",
      "Once every campaign on every channel has a role, two things become visible that no single-channel " +
        "report shows. The first is the double-pay risk: two or three channels all retargeting the same warm " +
        "pool, driving up blended CPA without any single report flagging anything odd, because within each " +
        "channel on its own the retargeting campaign looks like it is performing fine. The second is the " +
        "growth ceiling: a portfolio made up mostly of retargeting and branded capture, with no campaign " +
        "tapping new demand, stops growing once the existing pool is sold through, and that pattern only " +
        "becomes visible once you lay every channel side by side.",
      "What this delivers in practice depends on how much audience data is available: on Google Ads the " +
        "role classification is complete today, since brand terms and campaign type are simply in the data " +
        "every account already has. On Meta and LinkedIn that same classification is only as good as the " +
        "audience data underneath it, and grows as that gets read more deeply. An unrecognized campaign " +
        "deliberately comes back as \"unknown\" instead of being guessed: in channel synergy, a wrong guess " +
        "is more expensive than an honest \"we don't know yet\".",
    ],
    // Sluit direct aan op de "no limit on accounts, cross-channel synergy"-claim op de homepage --
    // dit artikel is de onderbouwing van precies die zin.
    gerelateerdeSlugs: ["acht-kpi-relaties-die-rapportages-missen", "attributie-zonder-trackingcode"],
    gerelateerdePaginas: [{ label: "No limit on accounts, cross-channel by default", href: "/" }],
  },
  {
    slug: "rsa-asset-dubbeltelling",
    titel: "The asset trap in RSA reporting: when your top line is a double count",
    samenvatting:
      "Most RSA analysis stops at the ad group level. Go one layer deeper, to individual assets, and you can walk into a double count that makes your best headline look worse than it is.",
    datum: "2026-08-04",
    leesminuten: 6,
    inhoud: [
      "A Responsive Search Ad is not one piece of ad copy but a pool of headlines and descriptions that " +
        "Google combines itself. Most reporting stops at the ad group level: how does this RSA perform as a " +
        "whole. That misses exactly the level where the real question sits, namely which individual headline " +
        "or description is doing the work.",
      "Go one layer deeper, to performance per asset, and there is a reason few specialists do this " +
        "structurally: the same impression, click, or conversion counts toward every asset that was in that " +
        "specific combination. A headline that happened to be shown often alongside a strong second headline " +
        "looks better than it is on its own. Without a hierarchy that corrects for that, \"our best-performing " +
        "headline\" ends up as a conclusion that mostly says something about who happened to stand next to it.",
      "The fix is not complicated statistics, but discipline in reading order: first keep the combinations " +
        "that occurred most often separate from combinations rarely shown, and only then judge an asset on " +
        "its own merits, not on the average of every combination it ever appeared in. Skip that hierarchy and " +
        "you optimize on noise that looks like a pattern.",
      "It is the same reason copy analysis at the asset level (the Meta equivalent is called creative " +
        "fatigue, a different mechanism with the same symptom: a good number telling the wrong story) " +
        "deserves its own kind of attention, separate from ordinary ad group reporting. It is not more work " +
        "for its own sake, it is the place where the double count otherwise goes unnoticed.",
    ],
    // Geen productpagina hoort hier logisch bij -- dit is een technisch RSA-detail zonder directe
    // pitch-match, en een gedwongen link zou precies het soort ruis zijn die dit artikel afraadt.
    gerelateerdeSlugs: ["acht-kpi-relaties-die-rapportages-missen", "gemiddelde-cpa-verkeerde-vraag"],
  },
  {
    slug: "acht-kpi-relaties-die-rapportages-missen",
    titel: "Eight KPI relationships most reports never set against each other",
    samenvatting:
      "A report usually lists CPA, CTR, and reach separately. The signal is often not in either one, but in the ratio between them.",
    datum: "2026-08-10",
    leesminuten: 7,
    inhoud: [
      "Most reports treat every KPI as its own line: CPA this month, CTR this month, reach this month. Read " +
        "on their own, none of the three says anything is wrong, and yet the combination can hide a problem " +
        "that only becomes visible once you set two KPIs explicitly against each other.",
      "A few concrete examples. CPA decomposition splits a risen CPA into its two possible causes, a dropped " +
        "CTR or a risen CPC, because the follow-up step differs for each. A promise gap sets the message in " +
        "the ad against what the landing page actually delivers: a high CTR with a low conversion rate is " +
        "often not a targeting problem but an expectations problem. Vanity engagement flags a campaign with " +
        "lots of interaction and little value, the kind of number that looks good in a report and does " +
        "nothing for revenue.",
      "The other five follow the same logic: saturation (repeated exposure to the same people with no extra " +
        "return), reach dilution (growing reach with declining relevance per person), value mix (conversions " +
        "rising in count but dropping in value), frequency-versus-reach (frequency climbing while reach stays " +
        "flat, a sign the audience is exhausted), and expensive visibility (a top placement that costs more " +
        "than it returns in extra conversions). Eight relationships, and none of them are visible in a report " +
        "that lists every KPI separately.",
      "What they have in common: every relationship revolves around two metrics that almost never appear on " +
        "the same row of a report, let alone get set against each other explicitly. That is not unwillingness " +
        "on the part of whoever builds the report, it is simply not what a standard overview is built for. It " +
        "is, however, exactly where the next decision comes from.",
    ],
    // Dit artikel is de meest directe onderbouwing van de eigen tagline ("a chart is not a
    // decision"): het is letterlijk het argument waarom losse KPI's geen antwoord zijn.
    gerelateerdeSlugs: ["gemiddelde-cpa-verkeerde-vraag", "impression-share-dashboard-vertelt-niet"],
    gerelateerdePaginas: [{ label: "A chart is not a decision", href: "/" }],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
