-- Sprint Hypotheses: generated by monthly analysis, pending approval
CREATE TABLE IF NOT EXISTS sprint_hypotheses (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  client_id text NOT NULL,
  analysis_id uuid,
  hypothesis text NOT NULL,
  expected_result text,
  measurement_metric text,
  timeframe text,
  rationale text,
  ice_impact numeric DEFAULT 0,
  ice_confidence numeric DEFAULT 0,
  ice_ease numeric DEFAULT 0,
  ice_total numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'pending', -- pending, accepted, rejected, completed
  accepted_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sh_client ON sprint_hypotheses(client_id, status);

-- Sprint Items: concrete tasks linked to hypotheses
CREATE TABLE IF NOT EXISTS sprint_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  client_id text NOT NULL,
  hypothesis_id uuid REFERENCES sprint_hypotheses(id) ON DELETE SET NULL,
  week_number integer,
  task text NOT NULL,
  status text NOT NULL DEFAULT 'todo', -- todo, in_planning, ongoing, done, backlog, expired
  -- Een ROL, geen naam. Hier stond de merknaam zelf, waardoor elke rij die zonder eigenaar
  -- werd weggeschreven de merknaam van dat moment kreeg — en bij een rebranding dus als
  -- klant-taak zou gaan tellen. LET OP: dit bestand aanpassen verandert een BESTAANDE database
  -- niet; daar staat de oude standaard nog tot er een ALTER overheen gaat.
  owner text DEFAULT 'Bureau',
  metrics text,
  review_timeframe text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_si_client ON sprint_items(client_id, status);
CREATE INDEX IF NOT EXISTS idx_si_hypothesis ON sprint_items(hypothesis_id);
